### ISSUE TITLE
Investigate need to use promisify with bedrock.events.emit

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/bedrock#32]
https://github.com/digitalbazaar/bedrock-express/pull/9 switched from async lib to async/await.  The `bedrock.events.emit` call had to be wrapped in `promisify` for it to function. Investigate if or why that is needed.

**Comment by mattcollier** [comment]
The issue here is that the current `emit` implementation will treat the last parameter as a callback function if it *is* a function.  This behavior is by design and is documented here: https://github.com/digitalbazaar/bedrock/blob/f4fc94a2ecdc482e1906c07d0c7e5af19775ec41/lib/events.js#L19-L23

Here is the offending API call in bedrock-express where `server` (a function) is passed in as the second (and last) parameter: https://github.com/digitalbazaar/bedrock-express/blob/async/lib/index.js#L68

Investigating possible remediations now.

**Comment by dlongley** [comment]
Perhaps requiring at least 3 parameters in order to use `callback` would work. Really, we should work on making the API simpler so can't call it with more than 3 parameters -- and if you use 3 parameters, the last one can be assumed to be the callback.

**Comment by mattcollier** [comment]
@dlongley doesn't your suggestion imply that we do not have existing API calls like `emit('bedrock.foo', callback);`  Whereby the second argument is legitimately a callback.  

I assume we are not wanting to make a breaking change here, so I'm puzzled as to how we get to `emit('bedrock.foo', oneParameter, optionalCallback);`

Can you flesh out your idea a bit more?

**Comment by dlongley** [comment]
> ...doesn't your suggestion imply that we do not have existing API calls like emit('bedrock.foo', callback); Whereby the second argument is legitimately a callback.

Yes, it does imply that -- I was hoping it was true. It's not.

Another option could be to check to see if the passed `function` has additional properties beyond being a regular function. If `Object.keys(lastArg).length > 0` returns true, we could assume it's not a regular callback function and is instead event data to be passed.
