### ISSUE TITLE
Watch lodash Per Method Packages

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock#74]
With the major release of `bedrock 4` we have started to use lodash per method packages.

https://github.com/digitalbazaar/bedrock/blob/3af349a9d95703e6340f51448fff89b972939bff/package.json#L33-L36

However the maintainer of lodash has already declared they will be removing these packages with the release of `lodash 5`:

https://lodash.com/per-method-packages

> Per Method Packages
> Lodash methods are available in standalone per method packages like lodash.mapvalues, lodash.pickby, etc. These packages contain only the code the method depends on.
> 
> However, use of these packages is discouraged and they will be removed in v5.

What removed means is questionable, but in this github issue one of the maintainers of lodash says:

https://github.com/lodash/lodash/issues/3838

> The individual module packages won't be carried over to Lodash v5. I can't deprecate them with the npm deprecate method since that sends a log to stderr and causes some build scripts to fail. So I will simply let it fade away without a v5 update.

**What this means is if a security vulnerability is found in any of the lodash method packages we are using there will be no support from the maintainer after lodash 5 is released.** Removed could possibly mean the packages will be removed from npm entirely in the future however it appears removed just means they will not be part of lodash 5.

As a reminder the current version of lodash is `4` and the per method packages will be removed after the release of  `5`. 
I could not find a roadmap for lodash 5's release. Version 4 was released July 10 2019.

**Comment by dlongley** [comment]
Possible outcomes from our decision to use the split up lodash packages:

1. Snyk/etc. continue to report CVEs on split up lodash packages and lodash maintainers keep updating them. This could happen just because lodash decided to do it or because of overwhelming community pressure to do so.
2. Snyk/etc. continue to report CVEs on split up lodash packages and lodash maintainers don't keep updating them.
3. Snyk/etc. report lodash packages are deprecated, stop reporting CVEs, and lodash maintainers don't keep updating them.

In case 1, it's a no-op for us and the best outcome. We don't have to deal with CVEs for lodash functionality we don't use.

In case 2 or 3, we have to make a decision to fork the packages or upgrade to lodash 5 -- it's an internal update and an annoyance because we're back into the situation we're in now, but at least we got a reprieve for a while.

I'm happy to hope for the best and we have a clear plan if we don't get it. I recommend we close this issue.

**Comment by aljones15** [comment]
I vote for keeping it open till `lodash 5` releases and we can see clearly what the future of the per method packages are. I'm subscribed to releases for `lodash` so I'd be more than happy to keep up. One thing not considered is that there might be CVEs in these packages as they don't depend on lodash directly, but contain separate copies of various lodash methods.

**Comment by aljones15** [comment]
ok so update:

https://github.com/lodash/lodash/issues/3943

The maintainer of the per method packages stopped maintaining them in 2018.

Additionally the per method packages may contain the CVE prototype pollution.
In other words we took a step back to get around getting flagged with CVEs and might have ended up
with the CVE vulnerabilities instead. The per method packages were not flagged with the CVEs is appears.


https://github.com/lodash/lodash/issues/3943#issuecomment-418998293

> Yes, individual modularized packages have not been updated in a while. The issue you referenced is of and only a possible problem when handling unsanitized user input. I've generally considered individual modularized packages as deprecated but will likely give them another rev with this latest round of upcoming security updates.

**Comment by dlongley** [comment]
lodash is being removed in v6, closing.
